In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6]])
x.ndim

2

In [4]:
x.dtype

dtype('int32')

In [5]:
x.shape

(2, 3)

In [6]:
x_reshape = x.reshape((1,6))
x_reshape
y = np.array([1,2,3,4,5])
y.reshape((5,))

array([1, 2, 3, 4, 5])

In [7]:
# N(50, 1)
np.random.normal(loc = 50, scale = 1, size = 50)

array([52.67725057, 51.29177611, 50.34026012, 50.20750763, 49.053555  ,
       49.83400461, 51.42685619, 50.2915161 , 49.55478249, 51.1455283 ,
       51.16861513, 49.73008419, 50.2321865 , 49.79630485, 49.58315326,
       50.0907948 , 51.27852824, 49.27820848, 51.38037159, 51.82289248,
       50.18257666, 49.15923003, 49.49725833, 50.03510016, 48.35339078,
       47.8090942 , 51.19024049, 51.06670382, 49.94475466, 49.47530328,
       49.31112597, 50.41531543, 50.45608842, 49.84657592, 49.54629623,
       48.78821906, 49.52131826, 50.4615158 , 50.66042059, 49.14094652,
       49.29763199, 50.20530713, 50.99914287, 50.99781274, 47.88021873,
       49.49160605, 51.88087464, 49.22851009, 50.23140992, 50.12093125])

In [8]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=6))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=6))

[  4.09482632  -1.07485605 -10.15364596   1.13406146  -4.14030566
  -4.74859823]
[  4.09482632  -1.07485605 -10.15364596   1.13406146  -4.14030566
  -4.74859823]


In [9]:
X = rng.standard_normal((10, 3))
X

array([[ 0.09748025,  1.13071035, -0.503177  ],
       [-1.6146684 , -0.51143783,  1.30857567],
       [-0.60106271, -1.04358358, -0.77787108],
       [-0.03621124, -2.366124  , -0.12532525],
       [-1.04473968, -0.46412883,  0.33555586],
       [-0.11933931, -0.19707608, -0.35307465],
       [ 0.09562671,  0.83201011,  1.78919398],
       [-3.25891725,  1.06043415, -0.69168156],
       [-1.16488556,  0.99099849, -1.18854665],
       [-0.41757888,  0.37701782,  1.49556003]])

In [10]:
# rows
X.mean(axis=1)

array([ 0.2416712 , -0.27251019, -0.80750579, -0.84255349, -0.39110422,
       -0.22316335,  0.90561027, -0.96338822, -0.45414457,  0.48499966])

In [11]:
# cols
X.mean(axis=0)

array([-0.80642961, -0.01911794,  0.12892093])

Sequence and Slice Notation

In [12]:
# equal spacing between elements, end value is included
s = 0
e = 10
n = 16
seq1 = np.linspace(s, e, n)
seq1


array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [13]:
div1 = (e - s)/(n - 1)
div1

0.6666666666666666

In [14]:
# similar to range()
seq2 = np.arange(0, 10, 2)
seq2

array([0, 2, 4, 6, 8])

Indexing Data

In [15]:
A  = np.array(np.arange(16)).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
# 2nd row 3rd column
A[1,2]

6

In [17]:
# multiple rows
A[[1,3]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [18]:
# multiple columns
A[:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [21]:
# multiple rows and columns
A[[0,2]][:, [1,3]]

array([[ 1,  3],
       [ 9, 11]])

In [23]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
idx = np.ix_([1,3], [0,1,2])
A[idx]

array([[ 4,  5,  6],
       [12, 13, 14]])

In [24]:
A[1:4:2,0:3:2]

array([[ 4,  6],
       [12, 14]])

Boolean Indexing

In [28]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

array([False, False, False, False])

In [29]:
keep_rows[[1,3]] = True
keep_rows


array([False,  True, False,  True])

In [31]:
np.all(keep_rows == np.array([0,1,0,1]))
# np.any() check if at leat one entry is true

True

In [32]:
# Different indexing
A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
# Different indexing
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [34]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [35]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])